#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 35003e98-b706-4f4d-a86f-8f59484a284e
# Source File: ..\..\SAPIEN\PowerShell Studio\Files\Account GUI Blank.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
LggAAB+LCAAAAAAABABlVkfL7AgOvBv6P3zMtWGcQ8ObB85u59gON9vtHNvZ/vXT+/aysDpJQgUC
UVX6ZWfpsGXTycVL/PNN5mro//kL/Rv+6/cN+Pn5ZUxVUfVxK1Rtpsdd9ptO02Htlx/Re/4wbdw3
f49z/gv8v7k/aGGYut9gQz7hOcWNOqRp1uBY+r/B0Fzrd7CLXaEFLkQEFpluImlx9TPRaJg9KL5A
7KiMehCoJcrFMIF0zsWpgih8A9rswrCSi9rymK2y7bTZteMSXMxpiacggFpQM1duD8F8d60mPwTK
yVuUmd0I47hh5chvDaV5gcnneQPs/Ios5ZOLa5HMT8YCyfKCZBvkXMswbew0zLDE6YPkcqt9c1cF
Fr3poYMJTpJL3o0VuaPRjoZSNxjlDSiDk+LlcTuCMw/kTDRL6tqFQ4srCa374pI/zqzlHj7AeGHH
tECyd00dpAPHA2zEObcK54fBeirFes0N0BI3sKSEJDg68iubsP13UaeEMDZKNHs5jR/mOR10+KBD
HVaDxfrwk2vuE6VpcoQ4kcpb2opFCf9coBsQui9DZWkNZ+rEGnI54H03P+Icbsry8FRZcY8jJh3H
Wtoq2h/V6ayRg42900EoNWb1jpTzs621me6lG2DSh6Epaxo1YnOmknZ1ZrCMfKMQl80YoQfpmcqU
Q/ZQNzWJ8JmFcUc/k8tRuJV7hvFz4icYKmBbkLUbkKgedDT3I71LJqY1cRzCvlbYupIHVoEiRWji
JSnpD2a7xFgtqMG7v3iEXgW3hz4vnwQfG2vkcTFBCH0DJKiCwTeVvPvXa6K7wjqpI5uV8RT6HqE3
uuPEfueko2gpiFEpUVNidXTZCMPEFLcH3uUTanX9eG7Z8QasePmWT6mHlXvqQ0SD16Y+wmFmk8Pi
RPJqk5KmykPjTC8+HEmI8eAYOZbabCgxW7X6QNZKyYQZd9z8BjgMUyWUkptuzZAbEmaj3UKId+l3
KM9BQhy4k8n6eJKeIg9/hmjURtW3LqfMtU6QRpt7thWkwiaS890NyCYmYuSgRp0Xsn+v8R5J79m1
Isiwdx7F0C3UaHlm9NguX1DJgwuPgFFHTLE3pa6+i7aakL7zcqVRJ28A0xwGrchSYTMHa/PCrvlX
ljPTy9436wrx9IBeIvMmbKF31eg/7Ca+7B66gO+8rmXqp0aYqovIuut9mXV88qt0XehOk2SKV0vx
Rpp+Ii6Y44XtWc2BtBKxMS5W3EKNT8NItoqyq/BSndccyx9Pq1VeDgO2kmvdAMTl3w/+HBqjmk1m
HSwDxnXzwfROXwYbaqO6oc4va5dhWkf1emn3srtywdboRVNoFW5CA998bY/RcbgBT7yGsf4ehEIE
O7WDPLaQRJdBMKMeFNqVHHvdOR2WiRuWC8a2gTj7yRRdt/YqY9wrEl4eaIuiQd19phtwIXeSmPI3
RsZTMwmdLn3aZV2jCxNaYXS2PRmhc1ihMT0Q/kLDs9dJuLOS8EEJ1+Usva3OUN7ADK+gN8DQWyk9
im4has542NNTccl0T5R3V9uxT8ipr3PSQ8reWVuRChh8lDVYidWABvyN1c8mELu1G8JuRNL6Brjm
Ih1MQMCEXl3x674Hm7e3X9hdTac2O/OEuTLSXYJVoTeomabu7rhqcnR1BSFxj7EMGLiHGoN90N4A
oko8wxe2Q6kQKl4LN2XE1vi8BsEWjZOVvFJEwEz3LncRd6vbU+09EEd7D6nc4h9te8BshqPho8/v
2A1QXxWePGSUa1ADP1IWVpILl/V0aaWP7a9OhRvcB14StkzirYtwB7KtzXKureejDNrvGZ5N665v
cRISNwCiVs0oEc2g6wDnFOr81O7iNAMyuqNB55Y9MmtedQZ8maLCaK5ZsvZYraYfcXFbLct7SfSY
6bnOrL8a8prFNAWFMLNSEtvj8+O3H+55pXeN2KFPj2XNkIN2jic8WOfpclG8jSWTvR3qtEaB8qK/
MoqB5XI+ku9u7yGyyruGI8FHWkAQ8saZgglG4T2E49pN4Wu/RhlHoSpwn/DBcho32cL68cAiYgUX
kKkXJDZrAoqJr5IPbIgbB8LF5uOtSCMKRXhJwaf66TzI9QcUdqheQ8jYgV8xH1Nia2/nmYAMwYEq
kpjTHz+m//nnF/jHpv8YNj3PWZe0VTb/gN/OL/B//4Pf/wJLSU2RLggAAA==#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.152
     Generated on:       5/24/2018 2:54 PM
     Generated by:       dfindley
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Account_GUI_Blank_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formAccountCreation = New-Object 'System.Windows.Forms.Form'
	$statusbar1 = New-Object 'System.Windows.Forms.StatusBar'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonNo = New-Object 'System.Windows.Forms.Button'
	$buttonYes = New-Object 'System.Windows.Forms.Button'
	$labelContinueWithTheseSet = New-Object 'System.Windows.Forms.Label'
	$textbox5 = New-Object 'System.Windows.Forms.TextBox'
	$labelTeamName = New-Object 'System.Windows.Forms.Label'
	$textbox4 = New-Object 'System.Windows.Forms.TextBox'
	$labelJobTitle = New-Object 'System.Windows.Forms.Label'
	$textbox3 = New-Object 'System.Windows.Forms.TextBox'
	$labelUsername = New-Object 'System.Windows.Forms.Label'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonCancel = New-Object 'System.Windows.Forms.Button'
	$buttonContinue = New-Object 'System.Windows.Forms.Button'
	$textbox2 = New-Object 'System.Windows.Forms.TextBox'
	$labelEnterLastName = New-Object 'System.Windows.Forms.Label'
	$labelEnterFirstName = New-Object 'System.Windows.Forms.Label'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$menustrip1 = New-Object 'System.Windows.Forms.MenuStrip'
	$errorprovider1 = New-Object 'System.Windows.Forms.ErrorProvider'
	$fileToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$exitToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$helpToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$aboutToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formAccountCreation_Load={
		#TODO: Initialize Form Controls here
		Import-Module ActiveDirectory
	}
	
	$groupbox1_Enter={
		#TODO: Place custom script here
		
	}
	
	$buttonContinue_Click={
		#TODO: Place custom script here
		$FirstName = $textbox1.Text
		$LastName = $textbox2.Text
		$UserName = $($FirstName.Substring(0, 1) + $LastName).ToLower()
		$textbox3.Text = $UserName
		$Account = (dsquery user -samid $UserName)
		
		if ($Account -eq $null)
		{
		$statusbar1.Text = "Username, $UserName, is available for use. "
		}
		else
		{
		$ErrorMessage = "Username, $UserName, is not available. Please manually enter one."
		$errorprovider1.SetIconAlignment($textbox3, 'MiddleRight')
		$errorprovider1.SetError($textbox3,($ErrorMessage))
		$statusbar1.Text = $ErrorMessage	
		}
	}
	
	$textbox3_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$buttonCancel_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonYes_Click={
		#TODO: Place custom script here
		$textbox3.Text = $UserName
		$FirstName = $textbox1.Text
		$LastName = $textbox2.Text
		$FullName = "$FirstName " + "$LastName"
		$SamAccountName = $UserName
		$GivenName = $FirstName
		$Surname = $LastName
		$EmailAddress = "$UserName @company.com"
		$StreetAddress = "12345 S. Road"
		$City = "City"
		$State = "State"
		$Company = "Company Name"
		$PhoneNumber = "555-555-5555"
		$AccountName = $UserName
		$AccountPass = "password"
		$EncryptPass = convertto-securestring $AccountPass -asplaintext -force
		$JobTitle = $textbox4.Text
		$TeamName = $textbox5.Text
		$UserName = $($FirstName.Substring(0, 1) + $LastName).ToLower()
		$Department = $textbox4.Text
		
		New-ADUser -Name $FullName `
				   -SamAccountName $SamAccountName `
				   -GivenName $GivenName
		
		Get-ADUser $UserName | Set-ADUser -GivenName $FirstName `
										  -Surname $LastName `
										  -EmailAddress $EmailAddress `
										  -Company $Company `
										  -UserPrincipalName "$UserName@companydomain.com" `
										  -Enable $true `
										  -DisplayName "$FirstName $LastName" `
										  -ChangePasswordAtLogon:$false `
										  -Title $JobTitle `
										  -MobilePhone $PhoneNumber `
										  -PasswordNeverExpires $true
	}
	
	$textbox5_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$exitToolStripMenuItem_Click={
		#TODO: Place custom script here
		$formAccountCreation.Close()
		
	}
	
	$aboutToolStripMenuItem_Click={
		#TODO: Place custom script here
		#------------------------------------------------------------------------
		# Source File Information (DO NOT MODIFY)
		# Source ID: 9a2aa374-bb49-4c52-a506-4dacee24e610
		# Source File: C:\Users\dfindley\Documents\SAPIEN\PowerShell Studio\Files\About Blank.psf
		#------------------------------------------------------------------------
		
	<#
	    .NOTES
	    --------------------------------------------------------------------------------
	     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.152
	     Generated on:       5/24/2018 2:03 PM
	     Generated by:       dfindley
	    --------------------------------------------------------------------------------
	    .DESCRIPTION
	        GUI script generated by PowerShell Studio 2018
	#>
		
		
		#----------------------------------------------
		#region Application Functions
		#----------------------------------------------
		
		#endregion Application Functions
		
		#----------------------------------------------
		# Generated Form Function
		#----------------------------------------------
		function Show-About_Blank_psf
		{
			
			#----------------------------------------------
			#region Import the Assemblies
			#----------------------------------------------
			[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
			[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
			#endregion Import Assemblies
			
			#----------------------------------------------
			#region Generated Form Objects
			#----------------------------------------------
			[System.Windows.Forms.Application]::EnableVisualStyles()
			$formAbout = New-Object 'System.Windows.Forms.Form'
			$labelVersion10 = New-Object 'System.Windows.Forms.Label'
			$labelADAccountCreationToo = New-Object 'System.Windows.Forms.Label'
			$buttonOK = New-Object 'System.Windows.Forms.Button'
			$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
			#endregion Generated Form Objects
			
			#----------------------------------------------
			# User Generated Script
			#----------------------------------------------
			
			$formAbout_Load = {
				#TODO: Initialize Form Controls here
				
			}
			
			$labelADAccountCreationToo_Click = {
				#TODO: Place custom script here
				
			}
			
			# --End User Generated Script--
			#----------------------------------------------
			#region Generated Events
			#----------------------------------------------
			
			$Form_StateCorrection_Load =
			{
				#Correct the initial state of the form to prevent the .Net maximized form issue
				$formAbout.WindowState = $InitialFormWindowState
			}
			
			$Form_Cleanup_FormClosed =
			{
				#Remove all event handlers from the controls
				try
				{
					$labelADAccountCreationToo.remove_Click($labelADAccountCreationToo_Click)
					$formAbout.remove_Load($formAbout_Load)
					$formAbout.remove_Load($Form_StateCorrection_Load)
					$formAbout.remove_FormClosed($Form_Cleanup_FormClosed)
				}
				catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
			}
			#endregion Generated Events
			
			#----------------------------------------------
			#region Generated Form Code
			#----------------------------------------------
			$formAbout.SuspendLayout()
			#
			# formAbout
			#
			$formAbout.Controls.Add($labelVersion10)
			$formAbout.Controls.Add($labelADAccountCreationToo)
			$formAbout.Controls.Add($buttonOK)
			$formAbout.AcceptButton = $buttonOK
			$formAbout.AutoScaleDimensions = '6, 13'
			$formAbout.AutoScaleMode = 'Font'
			$formAbout.BackColor = 'WhiteSmoke'
			$formAbout.ClientSize = '284, 262'
			$formAbout.FormBorderStyle = 'FixedDialog'
			$formAbout.MaximizeBox = $False
			$formAbout.MinimizeBox = $False
			$formAbout.Name = 'formAbout'
			$formAbout.StartPosition = 'CenterScreen'
			$formAbout.Text = 'About'
			$formAbout.add_Load($formAbout_Load)
			#
			# labelVersion10
			#
			$labelVersion10.AutoSize = $True
			$labelVersion10.Location = '99, 97'
			$labelVersion10.Name = 'labelVersion10'
			$labelVersion10.Size = '64, 17'
			$labelVersion10.TabIndex = 2
			$labelVersion10.Text = 'Version 1.0 '
			$labelVersion10.UseCompatibleTextRendering = $True
			#
			# labelADAccountCreationToo
			#
			$labelADAccountCreationToo.AutoSize = $True
			$labelADAccountCreationToo.Location = '71, 80'
			$labelADAccountCreationToo.Name = 'labelADAccountCreationToo'
			$labelADAccountCreationToo.Size = '135, 17'
			$labelADAccountCreationToo.TabIndex = 1
			$labelADAccountCreationToo.Text = 'AD Account Creation Tool'
			$labelADAccountCreationToo.UseCompatibleTextRendering = $True
			$labelADAccountCreationToo.add_Click($labelADAccountCreationToo_Click)
			#
			# buttonOK
			#
			$buttonOK.Anchor = 'Bottom, Right'
			$buttonOK.DialogResult = 'OK'
			$buttonOK.Location = '197, 227'
			$buttonOK.Name = 'buttonOK'
			$buttonOK.Size = '75, 23'
			$buttonOK.TabIndex = 0
			$buttonOK.Text = '&OK'
			$buttonOK.UseCompatibleTextRendering = $True
			$buttonOK.UseVisualStyleBackColor = $True
			$formAbout.ResumeLayout()
			#endregion Generated Form Code
			
			#----------------------------------------------
			
			#Save the initial state of the form
			$InitialFormWindowState = $formAbout.WindowState
			#Init the OnLoad event to correct the initial state of the form
			$formAbout.add_Load($Form_StateCorrection_Load)
			#Clean up the control events
			$formAbout.add_FormClosed($Form_Cleanup_FormClosed)
			#Show the Form
			return $formAbout.ShowDialog()
			
		} #End Function
		
		#Call the form
		Show-About_Blank_psf | Out-Null
		
	
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formAccountCreation.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonYes.remove_Click($buttonYes_Click)
			$textbox5.remove_TextChanged($textbox5_TextChanged)
			$textbox3.remove_TextChanged($textbox3_TextChanged)
			$buttonCancel.remove_Click($buttonCancel_Click)
			$buttonContinue.remove_Click($buttonContinue_Click)
			$groupbox1.remove_Enter($groupbox1_Enter)
			$formAccountCreation.remove_Load($formAccountCreation_Load)
			$exitToolStripMenuItem.remove_Click($exitToolStripMenuItem_Click)
			$aboutToolStripMenuItem.remove_Click($aboutToolStripMenuItem_Click)
			$formAccountCreation.remove_Load($Form_StateCorrection_Load)
			$formAccountCreation.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formAccountCreation.SuspendLayout()
	$groupbox2.SuspendLayout()
	$groupbox1.SuspendLayout()
	$menustrip1.SuspendLayout()
	#
	# formAccountCreation
	#
	$formAccountCreation.Controls.Add($statusbar1)
	$formAccountCreation.Controls.Add($groupbox2)
	$formAccountCreation.Controls.Add($groupbox1)
	$formAccountCreation.Controls.Add($menustrip1)
	$formAccountCreation.AutoScaleDimensions = '6, 13'
	$formAccountCreation.AutoScaleMode = 'Font'
	$formAccountCreation.ClientSize = '868, 511'
	$formAccountCreation.MainMenuStrip = $menustrip1
	$formAccountCreation.Name = 'formAccountCreation'
	$formAccountCreation.Text = 'Account Creation'
	$formAccountCreation.add_Load($formAccountCreation_Load)
	#
	# statusbar1
	#
	$statusbar1.Font = 'Segoe UI, 9.75pt'
	$statusbar1.Location = '0, 489'
	$statusbar1.Name = 'statusbar1'
	$statusbar1.Size = '868, 22'
	$statusbar1.TabIndex = 2
	$statusbar1.Text = 'Account Creation Tool v1.1'
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($buttonNo)
	$groupbox2.Controls.Add($buttonYes)
	$groupbox2.Controls.Add($labelContinueWithTheseSet)
	$groupbox2.Controls.Add($textbox5)
	$groupbox2.Controls.Add($labelTeamName)
	$groupbox2.Controls.Add($textbox4)
	$groupbox2.Controls.Add($labelJobTitle)
	$groupbox2.Controls.Add($textbox3)
	$groupbox2.Controls.Add($labelUsername)
	$groupbox2.Font = 'Segoe UI, 9.75pt'
	$groupbox2.Location = '38, 187'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Size = '695, 187'
	$groupbox2.TabIndex = 1
	$groupbox2.TabStop = $False
	$groupbox2.Text = 'Account Details:'
	$groupbox2.UseCompatibleTextRendering = $True
	#
	# buttonNo
	#
	$buttonNo.Location = '528, 154'
	$buttonNo.Name = 'buttonNo'
	$buttonNo.Size = '75, 23'
	$buttonNo.TabIndex = 8
	$buttonNo.Text = 'No'
	$buttonNo.UseCompatibleTextRendering = $True
	$buttonNo.UseVisualStyleBackColor = $True
	#
	# buttonYes
	#
	$buttonYes.Location = '612, 154'
	$buttonYes.Name = 'buttonYes'
	$buttonYes.Size = '75, 23'
	$buttonYes.TabIndex = 7
	$buttonYes.Text = 'Yes'
	$buttonYes.UseCompatibleTextRendering = $True
	$buttonYes.UseVisualStyleBackColor = $True
	$buttonYes.add_Click($buttonYes_Click)
	#
	# labelContinueWithTheseSet
	#
	$labelContinueWithTheseSet.AutoSize = $True
	$labelContinueWithTheseSet.Location = '20, 154'
	$labelContinueWithTheseSet.Name = 'labelContinueWithTheseSet'
	$labelContinueWithTheseSet.Size = '178, 22'
	$labelContinueWithTheseSet.TabIndex = 6
	$labelContinueWithTheseSet.Text = 'Continue with these settings?'
	$labelContinueWithTheseSet.UseCompatibleTextRendering = $True
	#
	# textbox5
	#
	$textbox5.Location = '145, 104'
	$textbox5.Name = 'textbox5'
	$textbox5.Size = '186, 25'
	$textbox5.TabIndex = 5
	$textbox5.add_TextChanged($textbox5_TextChanged)
	#
	# labelTeamName
	#
	$labelTeamName.AutoSize = $True
	$labelTeamName.Location = '20, 103'
	$labelTeamName.Name = 'labelTeamName'
	$labelTeamName.Size = '79, 22'
	$labelTeamName.TabIndex = 4
	$labelTeamName.Text = 'Team Name:'
	$labelTeamName.UseCompatibleTextRendering = $True
	#
	# textbox4
	#
	$textbox4.Location = '145, 63'
	$textbox4.Name = 'textbox4'
	$textbox4.Size = '186, 25'
	$textbox4.TabIndex = 3
	#
	# labelJobTitle
	#
	$labelJobTitle.AutoSize = $True
	$labelJobTitle.Location = '20, 62'
	$labelJobTitle.Name = 'labelJobTitle'
	$labelJobTitle.Size = '57, 22'
	$labelJobTitle.TabIndex = 2
	$labelJobTitle.Text = 'Job Title:'
	$labelJobTitle.UseCompatibleTextRendering = $True
	#
	# textbox3
	#
	$textbox3.Location = '145, 22'
	$textbox3.Name = 'textbox3'
	$textbox3.Size = '186, 25'
	$textbox3.TabIndex = 1
	$textbox3.add_TextChanged($textbox3_TextChanged)
	#
	# labelUsername
	#
	$labelUsername.AutoSize = $True
	$labelUsername.Location = '20, 25'
	$labelUsername.Name = 'labelUsername'
	$labelUsername.Size = '67, 22'
	$labelUsername.TabIndex = 0
	$labelUsername.Text = 'Username:'
	$labelUsername.UseCompatibleTextRendering = $True
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($buttonCancel)
	$groupbox1.Controls.Add($buttonContinue)
	$groupbox1.Controls.Add($textbox2)
	$groupbox1.Controls.Add($labelEnterLastName)
	$groupbox1.Controls.Add($labelEnterFirstName)
	$groupbox1.Controls.Add($textbox1)
	$groupbox1.Font = 'Segoe UI, 9.75pt'
	$groupbox1.Location = '38, 44'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '695, 125'
	$groupbox1.TabIndex = 0
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'Enter Name:'
	$groupbox1.UseCompatibleTextRendering = $True
	$groupbox1.add_Enter($groupbox1_Enter)
	#
	# buttonCancel
	#
	$buttonCancel.DialogResult = 'Cancel'
	$buttonCancel.Location = '528, 96'
	$buttonCancel.Name = 'buttonCancel'
	$buttonCancel.Size = '75, 23'
	$buttonCancel.TabIndex = 5
	$buttonCancel.Text = 'Cancel'
	$buttonCancel.UseCompatibleTextRendering = $True
	$buttonCancel.UseVisualStyleBackColor = $True
	$buttonCancel.add_Click($buttonCancel_Click)
	#
	# buttonContinue
	#
	$buttonContinue.Location = '612, 96'
	$buttonContinue.Name = 'buttonContinue'
	$buttonContinue.Size = '75, 23'
	$buttonContinue.TabIndex = 4
	$buttonContinue.Text = 'Continue'
	$buttonContinue.UseCompatibleTextRendering = $True
	$buttonContinue.UseVisualStyleBackColor = $True
	$buttonContinue.add_Click($buttonContinue_Click)
	#
	# textbox2
	#
	$textbox2.Location = '145, 73'
	$textbox2.Name = 'textbox2'
	$textbox2.Size = '186, 25'
	$textbox2.TabIndex = 3
	#
	# labelEnterLastName
	#
	$labelEnterLastName.AutoSize = $True
	$labelEnterLastName.Location = '20, 76'
	$labelEnterLastName.Name = 'labelEnterLastName'
	$labelEnterLastName.Size = '104, 22'
	$labelEnterLastName.TabIndex = 2
	$labelEnterLastName.Text = 'Enter Last Name:'
	$labelEnterLastName.UseCompatibleTextRendering = $True
	#
	# labelEnterFirstName
	#
	$labelEnterFirstName.AutoSize = $True
	$labelEnterFirstName.Location = '20, 34'
	$labelEnterFirstName.Name = 'labelEnterFirstName'
	$labelEnterFirstName.Size = '106, 22'
	$labelEnterFirstName.TabIndex = 1
	$labelEnterFirstName.Text = 'Enter First Name:'
	$labelEnterFirstName.UseCompatibleTextRendering = $True
	#
	# textbox1
	#
	$textbox1.Location = '145, 31'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '186, 25'
	$textbox1.TabIndex = 0
	#
	# menustrip1
	#
	[void]$menustrip1.Items.Add($fileToolStripMenuItem)
	[void]$menustrip1.Items.Add($helpToolStripMenuItem)
	$menustrip1.Location = '0, 0'
	$menustrip1.Name = 'menustrip1'
	$menustrip1.Size = '868, 24'
	$menustrip1.TabIndex = 3
	$menustrip1.Text = 'menustrip1'
	#
	# errorprovider1
	#
	$errorprovider1.ContainerControl = $formAccountCreation
	#
	# fileToolStripMenuItem
	#
	[void]$fileToolStripMenuItem.DropDownItems.Add($exitToolStripMenuItem)
	$fileToolStripMenuItem.Name = 'fileToolStripMenuItem'
	$fileToolStripMenuItem.Size = '37, 20'
	$fileToolStripMenuItem.Text = 'File'
	#
	# exitToolStripMenuItem
	#
	$exitToolStripMenuItem.Name = 'exitToolStripMenuItem'
	$exitToolStripMenuItem.Size = '92, 22'
	$exitToolStripMenuItem.Text = 'Exit'
	$exitToolStripMenuItem.add_Click($exitToolStripMenuItem_Click)
	#
	# helpToolStripMenuItem
	#
	[void]$helpToolStripMenuItem.DropDownItems.Add($aboutToolStripMenuItem)
	$helpToolStripMenuItem.Name = 'helpToolStripMenuItem'
	$helpToolStripMenuItem.Size = '44, 20'
	$helpToolStripMenuItem.Text = 'Help'
	#
	# aboutToolStripMenuItem
	#
	$aboutToolStripMenuItem.Name = 'aboutToolStripMenuItem'
	$aboutToolStripMenuItem.Size = '107, 22'
	$aboutToolStripMenuItem.Text = 'About'
	$aboutToolStripMenuItem.add_Click($aboutToolStripMenuItem_Click)
	$menustrip1.ResumeLayout()
	$groupbox1.ResumeLayout()
	$groupbox2.ResumeLayout()
	$formAccountCreation.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formAccountCreation.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formAccountCreation.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formAccountCreation.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formAccountCreation.ShowDialog()

} #End Function

#Call the form
Show-Account_GUI_Blank_psf | Out-Null
